Android.bp: fix mesa include path (v2)
To avoid the following building errors:

FAILED: out/soong/build.ninja
out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -globFile out/soon
g/.bootstrap/build-globs.ninja -o out/soong/build.ninja Android.bp
error: external/minigbm/Android.bp:120:1: module "gralloc.minigbm_intel" variant "android_x86_64_shared": source path "external/mesa3d/include
" does not exist
error: external/minigbm/Android.bp:104:1: module "libminigbm_cros_gralloc" variant "android_x86_64_static": source path "external/mesa3d/inclu
de" does not exist
error: external/minigbm/Android.bp:137:1: module "gralloc.minigbm_meson" variant "android_x86_64_shared": source path "external/mesa3d/include
" does not exist
error: external/minigbm/Android.bp:113:1: module "gralloc.minigbm" variant "android_x86_64_shared": source path "external/mesa3d/include" does
 not exist

(v2) Changes due to commit
     a264847 ("minigbm: Cleanup Android.bp")

 Conflicts:
	Android.bp