Add framebuffer HAL implementation based on drm_framebuffer (v6)
(v1) original lambdadroid implementation

(v2) changes in drv.h due to following commits:
     48b4c08 ("minigbm: fix flags to align with GBM")
     6e6dc49 ("minigbm: virtio: restrict formats supported without 3D")

(v3) changes in drv.h due to aosp master branch minigbm implementation

NOTE: #define BO_USE_FRAMEBUFFER (1ull << 19) as the fist available bit

(v4) changes due to aosp updates in cros_gralloc_handle.h, drv.h, drv_priv.h

(v5) rename to drm_framebuffer.cc to avoid C building error

In file included from external/minigbm/cros_gralloc/gralloc0/drm_framebuffer.c:38:
external/minigbm/cros_gralloc/gralloc0/../cros_gralloc_handle.h:18:28: error: expected identifier or '('
struct cros_gralloc_handle : public native_handle_t {
                           ^
1 error generated.

(v6) include "../cros_gralloc_helpers.h" and use static_cast to fix build errors

FAILED: out/soong/.intermediates/external/minigbm/gralloc.minigbm/android_x86_64_shared/unstripped/gralloc.minigbm.so
...
ld.lld: error: undefined symbol: cros_gralloc_convert_handle(native_handle const*)
>>> referenced by drm_framebuffer.cc:240 (external/minigbm/cros_gralloc/gralloc0/drm_framebuffer.cc:240)
...
>>> referenced by drm_framebuffer.cc:363 (external/minigbm/cros_gralloc/gralloc0/drm_framebuffer.cc:363)
...
>>> did you mean: extern "C" cros_gralloc_convert_handle
>>> defined in: out/soong/.intermediates/external/minigbm/gralloc.minigbm/android_x86_64_shared/obj/external/minigbm/cros_gralloc/cros_gralloc_hel
pers.o

external/minigbm/cros_gralloc/gralloc0/drm_framebuffer.cc:111:26: error: cannot initialize a variable of type 'struct drm_framebuffer *' with an l
value of type 'void *'
        struct drm_framebuffer *fb = data;
                                ^    ~~~~
external/minigbm/cros_gralloc/gralloc0/drm_framebuffer.cc:304:7: error: assigning to 'struct drm_framebuffer *' from incompatible type 'void *'
        fb = calloc(1, sizeof(*fb));
             ^~~~~~~~~~~~~~~~~~~~~~
2 errors generated.