minigbm: Add const to the backend::name (v2)
... to avoid compile-time error on C++:

   error: ISO C++11 does not allow conversion from string
   literal to 'char *' [-Werror,-Wwritable-strings]

Signed-off-by: Roman Stratiienko <r.stratiienko@gmail.com>
Change-Id: I176eb657f72e92d6b5c7c3b25c78c56f776c20ab

(v2)
Resolution of conflict due to commit:
bf1f37f "drv: add drv_preload"

 Conflicts:
	drv_priv.h