dri.c: fix build for mesa 21.3
Changes due to mesa commit 2d58e31 ("dri_interface: remove gl header")

Fixes the following building errors:

external/minigbm/dri.c:519:2: error: use of undeclared identifier 'GLboolean'
        GLboolean ret = dri->image_extension->queryDmaBufFormatModifierAttribs(
        ^
external/minigbm/dri.c:521:7: error: use of undeclared identifier 'ret'
        if (!ret)
             ^
2 errors generated.