Add framebuffer HAL implementation based on drm_framebuffer (v5)
(v1) original lambdadroid implementation

(v2) changes in drv.h due to following commits:
     48b4c08 ("minigbm: fix flags to align with GBM")
     6e6dc49 ("minigbm: virtio: restrict formats supported without 3D")

(v3) changes in drv.h due to aosp master branch minigbm implementation

NOTE: #define BO_USE_FRAMEBUFFER (1ull << 19) as the fist available bit

(v4) changes due to aosp updates in cros_gralloc_handle.h, drv.h, drv_priv.h

(v5) rename to drm_framebuffer.cc to avoid C building errors

In file included from external/minigbm/cros_gralloc/gralloc0/drm_framebuffer.c:38:
external/minigbm/cros_gralloc/gralloc0/../cros_gralloc_handle.h:18:28: error: expected identifier or '('
struct cros_gralloc_handle : public native_handle_t {
                           ^
1 error generated.

 Conflicts:
	Android.bp